# Generated by Django 5.2.13 on 2026-04-20 00:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_index=True, default='', max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=20)),
                ('ie', models.CharField(blank=True, default='', max_length=32)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM_ANALISE', 'Em análise'), ('PAUSADO', 'Pausado'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo'], name='app_cliente_codigo_543761_idx'), models.Index(fields=['nome'], name='app_cliente_nome_f28e46_idx'), models.Index(fields=['cpf_cnpj'], name='app_cliente_cpf_cnp_5184d9_idx'), models.Index(fields=['situacao'], name='app_cliente_situaca_fffabf_idx')],
            },
        ),
    ]
