# Generated by Django 5.2.13 on 2026-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_escritorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
