# Generated by Django 5.2.13 on 2026-04-20 17:50

import app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_escritorio_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoExtrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(db_index=True, max_length=7)),
                ('conta_bancaria', models.CharField(blank=True, default='', max_length=120)),
                ('arquivo', models.FileField(max_length=255, upload_to=app.models._conciliador_upload_to)),
                ('tipo_arquivo', models.CharField(choices=[('CSV', 'CSV'), ('XLS', 'XLS'), ('XLSX', 'XLSX'), ('PDF', 'PDF')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('PROCESSANDO', 'Processando'), ('PROCESSADA', 'Processada'), ('ERRO', 'Erro')], default='ENVIADA', max_length=20)),
                ('configuracao', models.JSONField(blank=True, default=dict)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='app.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='app.escritorio')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegraConciliador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('texto_referencia', models.CharField(max_length=255)),
                ('tipo_comparacao', models.CharField(choices=[('CONTEM', 'Contém'), ('IGUAL', 'Igual'), ('COMECA_COM', 'Começa com')], default='CONTEM', max_length=20)),
                ('tipo_movimento', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=20)),
                ('categoria', models.CharField(blank=True, default='', max_length=120)),
                ('subcategoria', models.CharField(blank=True, default='', max_length=120)),
                ('codigo_historico', models.CharField(blank=True, default='', max_length=120)),
                ('conta_debito', models.CharField(blank=True, default='', max_length=120)),
                ('conta_credito', models.CharField(blank=True, default='', max_length=120)),
                ('aplicar_automatico', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(db_index=True, default=100)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_conciliador', to='app.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_conciliador', to='app.escritorio')),
            ],
            options={
                'ordering': ['prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoImportada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linha_origem', models.PositiveIntegerField(blank=True, null=True)),
                ('data_movimento', models.DateField(db_index=True)),
                ('descricao_original', models.TextField()),
                ('descricao_normalizada', models.TextField(blank=True, db_index=True, default='')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_movimento', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('AMBOS', 'Ambos')], db_index=True, max_length=20)),
                ('categoria', models.CharField(blank=True, default='', max_length=120)),
                ('subcategoria', models.CharField(blank=True, default='', max_length=120)),
                ('conta_debito', models.CharField(blank=True, default='', max_length=120)),
                ('conta_credito', models.CharField(blank=True, default='', max_length=120)),
                ('codigo_historico', models.CharField(blank=True, default='', max_length=120)),
                ('revisado_manual', models.BooleanField(db_index=True, default=False)),
                ('dados_brutos', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='app.importacaoextrato')),
                ('regra_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='app.regraconciliador')),
            ],
            options={
                'ordering': ['data_movimento', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importacaoextrato',
            index=models.Index(fields=['referencia'], name='app_importa_referen_15ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='importacaoextrato',
            index=models.Index(fields=['tipo_arquivo'], name='app_importa_tipo_ar_274016_idx'),
        ),
        migrations.AddIndex(
            model_name='importacaoextrato',
            index=models.Index(fields=['status'], name='app_importa_status_e0d320_idx'),
        ),
        migrations.AddIndex(
            model_name='regraconciliador',
            index=models.Index(fields=['escritorio', 'ativo', 'prioridade'], name='app_regraco_escrito_273a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='regraconciliador',
            index=models.Index(fields=['empresa', 'ativo'], name='app_regraco_empresa_af51c9_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaoimportada',
            index=models.Index(fields=['importacao', 'data_movimento'], name='app_transac_importa_095f28_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaoimportada',
            index=models.Index(fields=['importacao', 'tipo_movimento'], name='app_transac_importa_4a0e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaoimportada',
            index=models.Index(fields=['regra_aplicada'], name='app_transac_regra_a_7680d8_idx'),
        ),
    ]
