# Generated by Django 5.2.13 on 2026-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_perfilconciliacao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='perfilconciliacao',
            new_name='app_perfilc_escrito_fc491a_idx',
            old_name='app_perfilc_escritor_idx',
        ),
        migrations.RenameIndex(
            model_name='perfilconciliacao',
            new_name='app_perfilc_empresa_8bd48b_idx',
            old_name='app_perfilc_empresa_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='conta_contabil',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Conta contábil (cód. banco)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conta_corrente',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Conta corrente'),
        ),
    ]
