# Generated by Django 5.2.13 on 2026-05-01 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cliente_conta_corrente_conta_contabil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('banco', models.CharField(blank=True, default='', max_length=60)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('total_lancamentos', models.PositiveIntegerField(default=0)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato_historicos', to='app.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extrato_historicos', to='app.escritorio')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='app_extrato_empresa_d3eeb4_idx'), models.Index(fields=['escritorio', 'criado_em'], name='app_extrato_escrito_4ab99b_idx')],
            },
        ),
    ]
