# Generated by Django 5.2.13 on 2026-04-30 21:59

import app.models
import django.db.models.deletion
import services.secure_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_extrato_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigitalCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(max_length=255, storage=services.secure_storage.EncryptedFileSystemStorage(), upload_to=app.models._certificado_upload_to)),
                ('arquivo_original', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(choices=[('PFX', 'PFX'), ('P12', 'P12')], db_index=True, max_length=10)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('hash_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ativo', 'cliente__nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BANCARIA', 'Conta bancária'), ('CONTABIL', 'Conta contábil')], db_index=True, max_length=20)),
                ('apelido', models.CharField(blank=True, default='', max_length=120)),
                ('banco', models.CharField(blank=True, default='', max_length=120)),
                ('agencia', models.CharField(blank=True, default='', max_length=20)),
                ('numero', models.CharField(blank=True, default='', max_length=30)),
                ('codigo_contabil', models.CharField(blank=True, default='', max_length=40)),
                ('descricao_contabil', models.CharField(blank=True, default='', max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ativo', 'tipo', 'apelido', 'criado_em'],
            },
        ),
        migrations.AddField(
            model_name='certificadodigitalcliente',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado_digital', to='app.cliente'),
        ),
        migrations.AddField(
            model_name='contacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='app.cliente'),
        ),
        migrations.AddIndex(
            model_name='contacliente',
            index=models.Index(fields=['cliente', 'ativo'], name='app_contacl_cliente_5d41b4_idx'),
        ),
        migrations.AddIndex(
            model_name='contacliente',
            index=models.Index(fields=['cliente', 'tipo'], name='app_contacl_cliente_d45c39_idx'),
        ),
    ]
