# Generated by Django 5.2.13 on 2026-05-01 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoContabil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(db_index=True)),
                ('nome', models.CharField(max_length=255)),
                ('grupo', models.CharField(blank=True, default='', max_length=120)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_contabeis', to='app.escritorio')),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['escritorio', 'ativo', 'codigo'], name='app_histori_escrito_4ddd29_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('classificacao', models.CharField(blank=True, default='', max_length=60)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, default='', max_length=30)),
                ('natureza', models.CharField(blank=True, default='', max_length=80)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plano_contas', to='app.escritorio')),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['escritorio', 'ativo', 'codigo'], name='app_planoco_escrito_7adcb5_idx')],
            },
        ),
    ]
