# Generated by Django 5.2.13 on 2026-05-03 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoComponente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_componente', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('JUROS', 'Juros'), ('MULTA', 'Multa'), ('DESCONTO', 'Desconto'), ('OUTROS', 'Outros')], db_index=True, default='PRINCIPAL', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TarifaVinculoAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, default='SISTEMA', max_length=255)),
                ('origem', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual')], default='AUTOMATICA', max_length=20)),
                ('status_anterior', models.CharField(choices=[('NAO_APLICA', 'Não aplica'), ('ENCONTRADA', 'Encontrada'), ('AGRUPADA', 'Agrupada'), ('NAO_ENCONTRADA', 'Não encontrada')], default='NAO_APLICA', max_length=20)),
                ('status_novo', models.CharField(choices=[('NAO_APLICA', 'Não aplica'), ('ENCONTRADA', 'Encontrada'), ('AGRUPADA', 'Agrupada'), ('NAO_ENCONTRADA', 'Não encontrada')], default='NAO_APLICA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='transacaoimportada',
            name='confianca_vinculo',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='BAIXA', max_length=10),
        ),
        migrations.AddField(
            model_name='transacaoimportada',
            name='data_ocorrencia',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaoimportada',
            name='lancamento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_relacionados', to='app.transacaoimportada'),
        ),
        migrations.AddField(
            model_name='transacaoimportada',
            name='status_vinculo_tarifa',
            field=models.CharField(choices=[('NAO_APLICA', 'Não aplica'), ('ENCONTRADA', 'Encontrada'), ('AGRUPADA', 'Agrupada'), ('NAO_ENCONTRADA', 'Não encontrada')], db_index=True, default='NAO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='transacaoimportada',
            name='tipo_lancamento',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TARIFA', 'Tarifa'), ('TARIFA_AGRUPADA', 'Tarifa agrupada'), ('OUTRO', 'Outro')], db_index=True, default='PRINCIPAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transacaoimportada',
            index=models.Index(fields=['importacao', 'tipo_lancamento'], name='app_transac_importa_e477db_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaoimportada',
            index=models.Index(fields=['importacao', 'status_vinculo_tarifa'], name='app_transac_importa_b5f6f5_idx'),
        ),
        migrations.AddField(
            model_name='lancamentocomponente',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='app.transacaoimportada'),
        ),
        migrations.AddField(
            model_name='tarifavinculoauditoria',
            name='lancamento_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_tarifa_principal', to='app.transacaoimportada'),
        ),
        migrations.AddField(
            model_name='tarifavinculoauditoria',
            name='lancamento_tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_tarifa_relacionada', to='app.transacaoimportada'),
        ),
        migrations.AddIndex(
            model_name='lancamentocomponente',
            index=models.Index(fields=['lancamento', 'tipo_componente'], name='app_lancame_lancame_0e4398_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifavinculoauditoria',
            index=models.Index(fields=['lancamento_principal', 'criado_em'], name='app_tarifav_lancame_e34b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifavinculoauditoria',
            index=models.Index(fields=['lancamento_tarifa', 'criado_em'], name='app_tarifav_lancame_b8cc7a_idx'),
        ),
    ]
