# Generated by Django 5.2.13 on 2026-05-07 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cliente_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoConciliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='EM_ANDAMENTO', max_length=20)),
                ('banco', models.CharField(blank=True, default='', max_length=60)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('dados_lancamentos', models.JSONField(blank=True, default=list)),
                ('dados_comprovantes', models.JSONField(blank=True, default=list)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_conciliacao', to='app.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_conciliacao', to='app.escritorio')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
