# Generated by Django 5.2.13 on 2026-05-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_sessaoconciliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacliente',
            name='chave_pix',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contacliente',
            name='conta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='contacliente',
            name='digito',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contacliente',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('CORRENTE', 'Conta corrente'), ('POUPANCA', 'Poupança'), ('SALARIO', 'Salário'), ('CONJUNTA', 'Conjunta'), ('PIX', 'PIX'), ('OUTRA', 'Outra')], db_index=True, default='CORRENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='contacliente',
            name='titular',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
